/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dependencies

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.Dependency
import org.gradle.api.artifacts.dsl.DependencyHandler

fun DependencyHandler.implementation(dependencyNotation: Any): Dependency? = add("implementation", dependencyNotation)
fun DependencyHandler.testImplementation(dependencyNotation: Any): Dependency? = add("testImplementation", dependencyNotation)

fun DependencyHandler.kotlinScope() {
  implementation(platform(Kotlin.bom))
  implementation(Kotlin.stdlib)
  implementation(Kotlin.Kotlinx.serialization)
  implementation(Kotlin.Kotlinx.Coroutines.core)

  testImplementation(Kotlin.test)
  testImplementation(Kotlin.testJunit)
  testImplementation(Kotlin.Kotlinx.Coroutines.test)
}

object Kotlin {
  private const val kotlinVersion = "1.4.10"

  const val stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
  const val test = "org.jetbrains.kotlin:kotlin-test:$kotlinVersion"
  const val testJunit = "org.jetbrains.kotlin:kotlin-test-junit:$kotlinVersion"
  const val bom = "org.jetbrains.kotlin:kotlin-bom:$kotlinVersion"

  object Kotlinx {
    private const val kotlinxVersion = "1.4.1"
    private const val serializationVersion = "1.0.1"

    object Coroutines {
      const val core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxVersion"
      const val test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlinxVersion"
    }

    const val serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:$serializationVersion"
  }
}

class DependenciesPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    project.afterEvaluate {
      dependencies.apply {
        kotlinScope()
      }
    }
  }
}
