/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */
import dependencies.kotlinScope

plugins {
  id("dependencies.greeting")

  kotlin("plugin.serialization")
  kotlin("jvm")
  application
}

repositories {
  // Use jcenter for resolving dependencies.
  // You can declare any Maven/Ivy/file repository here.
  jcenter()
  mavenCentral()
}

dependencies {
  kotlinScope()
}

application {
  // Define the main class for the application.
  mainClassName = "echo.AppKt"
}
